# Generated by Django 5.0.4 on 2024-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_name_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=122),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(default='coding', max_length=122),
        ),
    ]
