# Generated by Django 5.0.4 on 2024-06-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_category_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
