# Generated by Django 5.0.4 on 2024-06-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='coding', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
